# Project: SeewoKiller
# Makefile created by Red Panda C++ 3.4.3279

CXX      = "g++.exe"
CC       = "gcc.exe"
WINDRES  = "windres.exe"
RM       = del /q /f
CD       = cd /d
LIBS     = "-LE:/devc++/.Mingw&Libs/curl-8.21.0_4-win64-mingw/lib" "-LE:/devc++/.Mingw&Libs/.a" "-Wl,--stack,12582912" "-lShell32" "-lOle32" "-lvfw32" "-lwinmm" "-lole32" "-luuid" "-lcurl" "-lwldap32" "-limm32" "E:/devc++/.Mingw&Libs/curl-8.21.0_4-win64-mingw/lib/libcurl.a" "E:/devc++/.Mingw&Libs/curl-8.21.0_4-win64-mingw/lib/libcurl.dll.a" "E:/devc++/.Mingw&Libs/.a/libarchive.a" "E:/devc++/.Mingw&Libs/.a/libconfig.dll.a" "E:/devc++/.Mingw&Libs/.a/libconfig++.dll.a"
INCS     = 
CXXINCS  = "-IE:/devc++/.Mingw&Libs/.include/libarchive" "-IE:/devc++/.Mingw&Libs/.include/libconfig" "-IE:/devc++/.Mingw&Libs/curl-8.21.0_4-win64-mingw/include"
CXXFLAGS = $(CXXINCS) "-g3" "-fno-ms-extensions" "-pipe" "-Wall" "-Werror=return-type" "-Werror=vla" "-Wno-narrowing" "-D_DEBUG"
CFLAGS   = $(INCS) "-g3" "-fno-ms-extensions" "-pipe" "-Wall" "-Werror=implicit-int" "-Werror=return-type" "-Werror=vla" "-D_DEBUG"
NASM_FLAGS   =  "-f" "elf64" "-g"
WINDRESFLAGS = 
RES      = SeewoKiller_private.res
OBJ      = CameraRec.o web.o cmdCtrl.o files.o .spl_WHSTU_Rainbow.o main.o game.o $(RES)
BIN      = SeewoKiller.exe
LINKOBJ  = "CameraRec.o" "web.o" "cmdCtrl.o" "files.o" ".spl_WHSTU_Rainbow.o" "main.o" "game.o" "SeewoKiller_private.res"
CLEANOBJ = "CameraRec.o" "web.o" "cmdCtrl.o" "files.o" ".spl_WHSTU_Rainbow.o" "main.o" "game.o" "SeewoKiller_private.res" "SeewoKiller.exe"

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) >NUL 2>&1

SeewoKiller.exe: $(OBJ)

	$(CXX) $(LINKOBJ) -o "SeewoKiller.exe" $(LIBS)

CameraRec.o: CameraRec.cpp cmdCtrl.h CameraRec.h main.h
	$(CXX) -c "CameraRec.cpp" -o "CameraRec.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

web.o: web.cpp files.h web.h main.h
	$(CXX) -c "web.cpp" -o "web.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

cmdCtrl.o: cmdCtrl.cpp cmdCtrl.h main.h
	$(CXX) -c "cmdCtrl.cpp" -o "cmdCtrl.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

files.o: files.cpp files.h cmdCtrl.h main.h
	$(CXX) -c "files.cpp" -o "files.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

.spl_WHSTU_Rainbow.o: .spl_WHSTU_Rainbow.cpp cmdCtrl.h SplashScreen.h main.h
	$(CXX) -c ".spl_WHSTU_Rainbow.cpp" -o ".spl_WHSTU_Rainbow.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

main.o: main.cpp files.h web.h cmdCtrl.h game.h CameraRec.h SeewoKiller_private.h SplashScreen.h main.h
	$(CXX) -c "main.cpp" -o "main.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

game.o: game.cpp cmdCtrl.h game.h main.h
	$(CXX) -c "game.cpp" -o "game.o" $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

SeewoKiller_private.res: SeewoKiller_private.rc 
	$(WINDRES) -i "SeewoKiller_private.rc" --input-format=rc -o "SeewoKiller_private.res" -O coff $(WINDRESFLAGS) 

