/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SEEWOKILLER_PRIVATE_H
#define SEEWOKILLER_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.-10.-7.-10"
#define VER_MAJOR	2
#define VER_MINOR	-10
#define VER_RELEASE	-7
#define VER_BUILD	-10
#define COMPANY_NAME	""
#define FILE_VERSION	"2.-10.-7.-10"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"2.-10.-7.-10"

#endif /*SEEWOKILLER_PRIVATE_H*/
