/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SLYTHERINOS_PRIVATE_H
#define SLYTHERINOS_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.2.1.7"
#define VER_MAJOR	1
#define VER_MINOR	2
#define VER_RELEASE	1
#define VER_BUILD	7
#define COMPANY_NAME	"WHSTU Studio"
#define FILE_VERSION	"1.2.1.7"
#define FILE_DESCRIPTION	"Ï£ÎÖ¿ËÐÇ"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Seewo Killer"
#define PRODUCT_VERSION	"1.2.1.7"

#endif /*SLYTHERINOS_PRIVATE_H*/
