/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SLYTHERINOS_PRIVATE_H
#define SLYTHERINOS_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"2.-10.-9.-8"
#define VER_MAJOR	2
#define VER_MINOR	-10
#define VER_RELEASE	-9
#define VER_BUILD	-8
#define COMPANY_NAME	"WHSTU Studio"
#define FILE_VERSION	"2.-10.-9.-8"
#define FILE_DESCRIPTION	"Ï£ÎÖ¿ËÐÇ"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"Copyright (C)2017-2024 WHSTU Studio"
#define LEGAL_TRADEMARKS	"(R)WHSTU Studio"
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Seewo Killer"
#define PRODUCT_VERSION	"2.-10.-9.-8"

#endif /*SLYTHERINOS_PRIVATE_H*/
