/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef SLYTHERINOS_PRIVATE_H
#define SLYTHERINOS_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.3.29"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	3
#define VER_BUILD	29
#define COMPANY_NAME	"WHSTU Studio"
#define FILE_VERSION	"1.1.3.29"
#define FILE_DESCRIPTION	"Developed by WHSTU"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Seewo Killer"
#define PRODUCT_VERSION	"1.1.3.29"

#endif /*SLYTHERINOS_PRIVATE_H*/
